name: Notify Discord on New Commits

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Commit Information
      id: commit-info
      run: echo "::set-output name=commit_info::$(git log -1 --pretty=format:'%h %s - %an')"

    - name: Send Discord Notification!
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.CENTOOR_BOT }}
      run: |
        curl -H "Content-Type: application/json" -X POST -d "{
            \"content\": \"New commit pushed to main branch\",
            \"embeds\": [
                {
                    \"title\": \"Commit Information\",
                    \"description\": \"Commit: ${{ steps.commit-info.outputs.commit_info }}\",
                    \"color\": 15158332
                }
            ]
        }" $DISCORD_WEBHOOK_URL
